vits_config = dict(
    # audio=audio_config,
    run_name="vits_thorsten-voice",
    batch_size=4,
    eval_batch_size=4,
    batch_group_size=5,
    num_loader_workers=1,
    num_eval_loader_workers=1,
    run_eval=True,
    test_delay_epochs=-1,
    epochs=1000,
    text_cleaner="phoneme_cleaners",
    use_phonemes=True,
    phoneme_language="de",
    # phoneme_cache_path=os.path.join(output_path, "phoneme_cache"),
    compute_input_seq_cache=True,
    print_step=25,
    print_eval=True,
    mixed_precision=False,
    # output_path=output_path,
    # datasets=[dataset_config],
    cudnn_benchmark=False,
    # test_sentences=[
    #     "Es hat mich viel Zeit gekostet ein Stimme zu entwickeln, jetzt wo ich sie habe werde ich nicht mehr schweigen.",
    #     "Sei eine Stimme, kein Echo.",
    #     "Es tut mir Leid David. Das kann ich leider nicht machen.",
    #     "Dieser Kuchen ist großartig. Er ist so lecker und feucht.",
    #     "Vor dem 22. November 1963.",
    # ],
)
